In [40]:
import yfinance as yf

# vanguard etfs
data = yf.download("VOX VCR VDC VIG VWOB VDE VSGX VCEB", start="1995-01-01", end="2022-12-31")

[*********************100%***********************]  8 of 8 completed

In [41]:
data

            Adj Close                                                  \
                 VCEB         VCR         VDC         VDE         VIG
Date
2004-01-30        NaN   39.020283   32.729828         NaN         NaN
2004-02-02        NaN   39.028324   32.749222         NaN         NaN
2004-02-03        NaN   38.875538   32.749222         NaN         NaN
2004-02-04        NaN   38.682518   33.201553         NaN         NaN
2004-02-05        NaN   38.980064   33.272629         NaN         NaN
...               ...         ...         ...         ...         ...
2022-12-23  60.506886  218.825546  192.407578  119.920471  151.264893
2022-12-27  59.898880  215.684647  193.194016  121.129082  151.483780
2022-12-28  59.785557  213.331467  190.725204  118.028290  149.921677
2022-12-29  60.093006  218.855453  191.680878  119.395409  151.802185
2022-12-30  59.790485  218.386810  190.705292  120.148323  151.085800

                                                 Close              ...  \
                  VOX       VSGX       VWOB       VCEB         VCR  ...
Date                                                                ...
2004-01-30        NaN        NaN        NaN        NaN   48.520000  ...
2004-02-02        NaN        NaN        NaN        NaN   48.529999  ...
2004-02-03        NaN        NaN        NaN        NaN   48.340000  ...
2004-02-04        NaN        NaN        NaN        NaN   48.099998  ...
2004-02-05        NaN        NaN        NaN        NaN   48.470001  ...
...               ...        ...        ...        ...         ...  ...
2022-12-23  81.736603  48.567719  60.036625  61.402000  219.460007  ...
2022-12-27  80.979042  48.784672  59.792336  60.785000  216.309998  ...
2022-12-28  79.782898  48.183125  59.460106  60.669998  213.949997  ...
2022-12-29  81.916023  49.021347  59.948681  60.981998  219.490005  ...
2022-12-30  81.985802  48.508549  59.587132  60.674999  219.020004  ...

                 Open              Volume                            \
                 VSGX       VWOB     VCEB     VCR     VDC       VDE
Date
2004-01-30        NaN        NaN      NaN  211800    6800       NaN
2004-02-02        NaN        NaN      NaN   10500     200       NaN
2004-02-03        NaN        NaN      NaN    1500       0       NaN
2004-02-04        NaN        NaN      NaN     400    3000       NaN
2004-02-05        NaN        NaN      NaN    3100     600       NaN
...               ...        ...      ...     ...     ...       ...
2022-12-23  49.080002  61.669998  21100.0  121400  111200  551000.0
2022-12-27  49.320000  61.259998  39900.0  175500  268100  519000.0
2022-12-28  49.450001  61.189999  22900.0  145900   96200  496200.0
2022-12-29  49.320000  61.060001  27500.0  159000  107900  442800.0
2022-12-30  49.320000  61.099998  26800.0  132600  100100  466000.0


                  VIG       VOX      VSGX      VWOB
Date
2004-01-30        NaN       NaN       NaN       NaN
2004-02-02        NaN       NaN       NaN       NaN
2004-02-03        NaN       NaN       NaN       NaN
2004-02-04        NaN       NaN       NaN       NaN
2004-02-05        NaN       NaN       NaN       NaN
...               ...       ...       ...       ...
2022-12-23  2074800.0  262500.0  148800.0  263100.0
2022-12-27  2068100.0  499200.0  317600.0  275500.0
2022-12-28  1570400.0  951900.0  295000.0  299100.0
2022-12-29  1578500.0  328400.0  436500.0  356400.0
2022-12-30  1855200.0  298200.0  214500.0  367500.0

[4764 rows x 48 columns]

In [59]:
import pandas as pd

data.to_csv('vanguard_etfs.csv')

In [66]:
df = pd.read_csv('vanguard_etfs.csv')

In [98]:
df.drop([1, 1])

,Unnamed: 0,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Close,...,Open.6,Open.7,Volume,Volume.1,Volume.2,Volume.3,Volume.4,Volume.5,Volume.6,Volume.7
0,NaN,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB,VCEB,...,VSGX,VWOB,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB
2,2004-01-30,NaN,39.02028274536133,32.729827880859375,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,211800,6800,NaN,NaN,NaN,NaN,NaN
3,2004-02-02,NaN,39.028324127197266,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10500,200,NaN,NaN,NaN,NaN,NaN
4,2004-02-03,NaN,38.87553787231445,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1500,0,NaN,NaN,NaN,NaN,NaN
5,2004-02-04,NaN,38.682518005371094,33.20155334472656,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,400,3000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4761,2022-12-23,60.50688552856445,218.82554626464844,192.40757751464844,119.92047119140625,151.264892578125,81.73660278320312,48.567718505859375,60.036624908447266,61.402000427246094,...,49.08000183105469,61.66999816894531,21100.0,121400,111200,551000.0,2074800.0,262500.0,148800.0,263100.0
4762,2022-12-27,59.89888000488281,215.6846466064453,193.1940155029297,121.12908172607422,151.48377990722656,80.97904205322266,48.784671783447266,59.792335510253906,60.78499984741211,...,49.31999969482422,61.2599983215332,39900.0,175500,268100,519000.0,2068100.0,499200.0,317600.0,275500.0
4763,2022-12-28,59.78555679321289,213.3314666748047,190.72520446777344,118.02828979492188,149.9216766357422,79.78289794921875,48.18312454223633,59.460105895996094,60.66999816894531,...,49.45000076293945,61.189998626708984,22900.0,145900,96200,496200.0,1570400.0,951900.0,295000.0,299100.0
4764,2022-12-29,60.0930061340332,218.85545349121094,191.68087768554688,119.3954086303711,151.80218505859375,81.91602325439453,49.02134704589844,59.94868087768555,60.981998443603516,...,49.31999969482422,61.060001373291016,27500.0,159000,107900,442800.0,1578500.0,328400.0,436500.0,356400.0
4765,2022-12-30,59.79048538208008,218.38681030273438,190.70529174804688,120.14832305908203,151.08580017089844,81.98580169677734,48.508548736572266,59.58713150024414,60.67499923706055,...,49.31999969482422,61.099998474121094,26800.0,132600,100100,466000.0,1855200.0,298200.0,214500.0,367500.0

In [105]:
df

,Unnamed: 0,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Close,...,Open.6,Open.7,Volume,Volume.1,Volume.2,Volume.3,Volume.4,Volume.5,Volume.6,Volume.7
0,NaN,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB,VCEB,...,VSGX,VWOB,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-30,NaN,39.02028274536133,32.729827880859375,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,211800,6800,NaN,NaN,NaN,NaN,NaN
3,2004-02-02,NaN,39.028324127197266,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10500,200,NaN,NaN,NaN,NaN,NaN
4,2004-02-03,NaN,38.87553787231445,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1500,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4761,2022-12-23,60.50688552856445,218.82554626464844,192.40757751464844,119.92047119140625,151.264892578125,81.73660278320312,48.567718505859375,60.036624908447266,61.402000427246094,...,49.08000183105469,61.66999816894531,21100.0,121400,111200,551000.0,2074800.0,262500.0,148800.0,263100.0
4762,2022-12-27,59.89888000488281,215.6846466064453,193.1940155029297,121.12908172607422,151.48377990722656,80.97904205322266,48.784671783447266,59.792335510253906,60.78499984741211,...,49.31999969482422,61.2599983215332,39900.0,175500,268100,519000.0,2068100.0,499200.0,317600.0,275500.0
4763,2022-12-28,59.78555679321289,213.3314666748047,190.72520446777344,118.02828979492188,149.9216766357422,79.78289794921875,48.18312454223633,59.460105895996094,60.66999816894531,...,49.45000076293945,61.189998626708984,22900.0,145900,96200,496200.0,1570400.0,951900.0,295000.0,299100.0
4764,2022-12-29,60.0930061340332,218.85545349121094,191.68087768554688,119.3954086303711,151.80218505859375,81.91602325439453,49.02134704589844,59.94868087768555,60.981998443603516,...,49.31999969482422,61.060001373291016,27500.0,159000,107900,442800.0,1578500.0,328400.0,436500.0,356400.0
4765,2022-12-30,59.79048538208008,218.38681030273438,190.70529174804688,120.14832305908203,151.08580017089844,81.98580169677734,48.508548736572266,59.58713150024414,60.67499923706055,...,49.31999969482422,61.099998474121094,26800.0,132600,100100,466000.0,1855200.0,298200.0,214500.0,367500.0

In [106]:
new_df = df.rename(columns={"Unnamed: 0": "Date"})

In [107]:
new_df

,Date,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Close,...,Open.6,Open.7,Volume,Volume.1,Volume.2,Volume.3,Volume.4,Volume.5,Volume.6,Volume.7
0,NaN,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB,VCEB,...,VSGX,VWOB,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-30,NaN,39.02028274536133,32.729827880859375,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,211800,6800,NaN,NaN,NaN,NaN,NaN
3,2004-02-02,NaN,39.028324127197266,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10500,200,NaN,NaN,NaN,NaN,NaN
4,2004-02-03,NaN,38.87553787231445,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1500,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4761,2022-12-23,60.50688552856445,218.82554626464844,192.40757751464844,119.92047119140625,151.264892578125,81.73660278320312,48.567718505859375,60.036624908447266,61.402000427246094,...,49.08000183105469,61.66999816894531,21100.0,121400,111200,551000.0,2074800.0,262500.0,148800.0,263100.0
4762,2022-12-27,59.89888000488281,215.6846466064453,193.1940155029297,121.12908172607422,151.48377990722656,80.97904205322266,48.784671783447266,59.792335510253906,60.78499984741211,...,49.31999969482422,61.2599983215332,39900.0,175500,268100,519000.0,2068100.0,499200.0,317600.0,275500.0
4763,2022-12-28,59.78555679321289,213.3314666748047,190.72520446777344,118.02828979492188,149.9216766357422,79.78289794921875,48.18312454223633,59.460105895996094,60.66999816894531,...,49.45000076293945,61.189998626708984,22900.0,145900,96200,496200.0,1570400.0,951900.0,295000.0,299100.0
4764,2022-12-29,60.0930061340332,218.85545349121094,191.68087768554688,119.3954086303711,151.80218505859375,81.91602325439453,49.02134704589844,59.94868087768555,60.981998443603516,...,49.31999969482422,61.060001373291016,27500.0,159000,107900,442800.0,1578500.0,328400.0,436500.0,356400.0
4765,2022-12-30,59.79048538208008,218.38681030273438,190.70529174804688,120.14832305908203,151.08580017089844,81.98580169677734,48.508548736572266,59.58713150024414,60.67499923706055,...,49.31999969482422,61.099998474121094,26800.0,132600,100100,466000.0,1855200.0,298200.0,214500.0,367500.0

In [114]:
new_df.to_csv('test.csv', index=False)

In [115]:
updated_df = new_df.drop([1, 1])

In [116]:
updated_df

,Date,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Close,...,Open.6,Open.7,Volume,Volume.1,Volume.2,Volume.3,Volume.4,Volume.5,Volume.6,Volume.7
0,NaN,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB,VCEB,...,VSGX,VWOB,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB
2,2004-01-30,NaN,39.02028274536133,32.729827880859375,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,211800,6800,NaN,NaN,NaN,NaN,NaN
3,2004-02-02,NaN,39.028324127197266,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10500,200,NaN,NaN,NaN,NaN,NaN
4,2004-02-03,NaN,38.87553787231445,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1500,0,NaN,NaN,NaN,NaN,NaN
5,2004-02-04,NaN,38.682518005371094,33.20155334472656,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,400,3000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4761,2022-12-23,60.50688552856445,218.82554626464844,192.40757751464844,119.92047119140625,151.264892578125,81.73660278320312,48.567718505859375,60.036624908447266,61.402000427246094,...,49.08000183105469,61.66999816894531,21100.0,121400,111200,551000.0,2074800.0,262500.0,148800.0,263100.0
4762,2022-12-27,59.89888000488281,215.6846466064453,193.1940155029297,121.12908172607422,151.48377990722656,80.97904205322266,48.784671783447266,59.792335510253906,60.78499984741211,...,49.31999969482422,61.2599983215332,39900.0,175500,268100,519000.0,2068100.0,499200.0,317600.0,275500.0
4763,2022-12-28,59.78555679321289,213.3314666748047,190.72520446777344,118.02828979492188,149.9216766357422,79.78289794921875,48.18312454223633,59.460105895996094,60.66999816894531,...,49.45000076293945,61.189998626708984,22900.0,145900,96200,496200.0,1570400.0,951900.0,295000.0,299100.0
4764,2022-12-29,60.0930061340332,218.85545349121094,191.68087768554688,119.3954086303711,151.80218505859375,81.91602325439453,49.02134704589844,59.94868087768555,60.981998443603516,...,49.31999969482422,61.060001373291016,27500.0,159000,107900,442800.0,1578500.0,328400.0,436500.0,356400.0
4765,2022-12-30,59.79048538208008,218.38681030273438,190.70529174804688,120.14832305908203,151.08580017089844,81.98580169677734,48.508548736572266,59.58713150024414,60.67499923706055,...,49.31999969482422,61.099998474121094,26800.0,132600,100100,466000.0,1855200.0,298200.0,214500.0,367500.0

In [119]:
updated_df.to_csv('vanguard_etfs.csv', index=False)

In [128]:
updated_df

,Date,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Close,...,Open.6,Open.7,Volume,Volume.1,Volume.2,Volume.3,Volume.4,Volume.5,Volume.6,Volume.7
0,NaN,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB,VCEB,...,VSGX,VWOB,VCEB,VCR,VDC,VDE,VIG,VOX,VSGX,VWOB
2,2004-01-30,NaN,39.02028274536133,32.729827880859375,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,211800,6800,NaN,NaN,NaN,NaN,NaN
3,2004-02-02,NaN,39.028324127197266,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10500,200,NaN,NaN,NaN,NaN,NaN
4,2004-02-03,NaN,38.87553787231445,32.74922180175781,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1500,0,NaN,NaN,NaN,NaN,NaN
5,2004-02-04,NaN,38.682518005371094,33.20155334472656,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,400,3000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4761,2022-12-23,60.50688552856445,218.82554626464844,192.40757751464844,119.92047119140625,151.264892578125,81.73660278320312,48.567718505859375,60.036624908447266,61.402000427246094,...,49.08000183105469,61.66999816894531,21100.0,121400,111200,551000.0,2074800.0,262500.0,148800.0,263100.0
4762,2022-12-27,59.89888000488281,215.6846466064453,193.1940155029297,121.12908172607422,151.48377990722656,80.97904205322266,48.784671783447266,59.792335510253906,60.78499984741211,...,49.31999969482422,61.2599983215332,39900.0,175500,268100,519000.0,2068100.0,499200.0,317600.0,275500.0
4763,2022-12-28,59.78555679321289,213.3314666748047,190.72520446777344,118.02828979492188,149.9216766357422,79.78289794921875,48.18312454223633,59.460105895996094,60.66999816894531,...,49.45000076293945,61.189998626708984,22900.0,145900,96200,496200.0,1570400.0,951900.0,295000.0,299100.0
4764,2022-12-29,60.0930061340332,218.85545349121094,191.68087768554688,119.3954086303711,151.80218505859375,81.91602325439453,49.02134704589844,59.94868087768555,60.981998443603516,...,49.31999969482422,61.060001373291016,27500.0,159000,107900,442800.0,1578500.0,328400.0,436500.0,356400.0
4765,2022-12-30,59.79048538208008,218.38681030273438,190.70529174804688,120.14832305908203,151.08580017089844,81.98580169677734,48.508548736572266,59.58713150024414,60.67499923706055,...,49.31999969482422,61.099998474121094,26800.0,132600,100100,466000.0,1855200.0,298200.0,214500.0,367500.0

In [133]:
# sorting by largest Adj Close.1 values
updated_df.groupby(['Date']).mean().sort_values('Adj Close.1', ascending=False)

,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Close,Close.1,...,Open.6,Open.7,Volume,Volume.1,Volume.2,Volume.3,Volume.4,Volume.5,Volume.6,Volume.7
Date,,,,,,,,,,,,,,,,,,,,,
2021-11-19,70.711418,350.861908,181.37262,72.292244,162.173218,138.187439,60.481369,71.746605,73.675003,355.630005,...,63.790001,77.879997,17500.0,1055500.0,80500.0,4115400.0,1365800.0,2838300.0,333200.0,99200.0
2021-11-05,71.532021,350.733612,183.978836,77.446579,162.299423,142.484543,61.061176,72.549118,74.529999,355.5,...,64.32,78.330002,8600.0,94700.0,508300.0,934400.0,1001000.0,95800.0,518300.0,291000.0
2021-11-18,70.501228,350.644806,182.222061,75.268425,162.648911,139.15329,60.795036,71.746605,73.456001,355.410004,...,64.0,77.57,4500.0,111200.0,106900.0,1070700.0,1281300.0,126000.0,169600.0,103900.0
2021-11-22,70.226715,349.381989,183.110077,73.447044,162.192657,136.699188,60.01561,71.119362,73.169998,354.130005,...,63.599998,77.589996,17100.0,834200.0,92300.0,1452400.0,1808800.0,1040700.0,239100.0,240800.0
2021-11-04,71.119316,348.020477,182.946014,76.216675,161.474289,141.035736,61.061176,71.995667,74.099998,352.75,...,64.300003,77.769997,90800.0,151600.0,142100.0,1174800.0,1132600.0,76000.0,455500.0,343400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-03-03,NaN,21.505224,33.566265,37.110851,23.445642,27.417662,NaN,NaN,NaN,25.370001,...,NaN,NaN,NaN,130700.0,278700.0,167000.0,521000.0,39100.0,NaN,NaN
2009-03-05,NaN,21.039005,33.165756,36.938625,22.925282,27.432083,NaN,NaN,NaN,24.82,...,NaN,NaN,NaN,94200.0,133300.0,202300.0,241200.0,43000.0,NaN,NaN
2009-03-06,NaN,20.860998,33.510036,37.579292,23.007063,27.295036,NaN,NaN,NaN,24.610001,...,NaN,NaN,NaN,120400.0,173400.0,188900.0,308600.0,50400.0,NaN,NaN
2009-03-09,NaN,20.572796,32.863602,37.50351,22.709703,26.37895,NaN,NaN,NaN,24.27,...,NaN,NaN,NaN,209000.0,98500.0,222100.0,294600.0,27500.0,NaN,NaN
2008-11-20,NaN,20.541723,36.289532,38.57563,25.61194,24.805719,NaN,NaN,NaN,24.83,...,NaN,NaN,NaN,117000.0,208800.0,239900.0,276600.0,14400.0,NaN,NaN

In [139]:
# sorting by smallest Adj Close.1 values
updated_df_final = updated_df.groupby(['Date']).mean().sort_values('Adj Close.1', ascending=True)

In [140]:
# saving initial data to excel workbook
data.to_excel('vanguard_etfs.xlsx')

# saving updated data to excel workbook and csv
updated_df_final.to_excel('vanguard_etfs_updated.xlsx')
updated_df_final.to_csv('vanguard_etfs_updated.csv')